FORMAT: 1A
HOST: private-01ace7-scout7.apiary-mock.com

# Scout

**API для приложения Scout**

- При создании, изменении записей  ключевое поле (в JSON-е тела запроса) стандартно игнорируется. 
  При создании его значение будет присвоено автоматически.  
- Если необходимо явно указать или изменить значение ключевого поля, это можно сделать с дополнительным параметром запроса unprotect_keys=true   
- При изменении записей в JSON-е тела запроса можно указывать только те поля, которые должны быть изменены.
- Операция `DELETE` состоит в установке значения поля `active` в false.

## Data Structures

### GroupsGoodsStructure
+ id_group: 4 (number, required)
+ name_group: Пополнение счета (string, required)
+ id_owner_group: 0 (number, required)
+ active: true (boolean, required)
+ id_image: 123 (number, required)
+ children: [] (array[GroupsGoodsStructure], required)

### GroupGoodsStructure
+ id_group: 4 (number, required)
+ id_owner_group: 0 (number, required)
+ name_group: Алкогольные напитки (string, required)
+ active: true (boolean, required)

### GoodsStructure
+ id_goods: 7 (number, required)
+ id_group: 1 (number, required)
+ id_tax: 1 (number, required)
+ name_goods: Чашка обычная (string, required)
+ sort_order: 7 (string, required)
+ id_printer: 1 (number, required),
+ type_goods: 0 (number, required),
+ active: true (boolean, required)

### GoodsAttrsStructure
+ id_goods: 7 (number, required)
+ control_rest: false (boolean, required)
+ permission_type: 0 (number,required)
+ extern_service_id: 1 (number, required, nullable)
+ print_name_goods: Чашка обычная (string, required)
+ free_price: false (boolean, required)
+ only_bar_code: false (boolean, required)
+ control_showcase: false (boolean, required)
+ min_order: 0.000 (number, required)
+ id_client: 1 (number, required, nullable)
+ use_series: false (boolean, required)
+ id_text: 1 (number, required, nullable)
+ id_modificator_group: 1 (number, required, nullable)

### BarCodesStructure
+ bar_code: 4052557303215 (string,required)
+ id_unit: 1 (number,required)
+ id_goods: 910 (number,required)
+ id_series: 1 (string,required)
+ ext_bar_code: 44 (string,required)
+ active: true (boolean, required)

### ClientsStructure
+ id_client: 8 (number, required)
+ name_client: Иванов (string, required)
+ is_supplier: false (boolean, required)
+ is_buyer: true (boolean, required)
+ can_return: true (boolean, required)
+ id_price_level: 2 (number, required)
+ active: true (boolean, required)

### TaxesStructure
+ id_tax: 1 (number, required)
+ rate_tax: 0.00 (number, required)
+ name_tax: Без НДС (string, required)
+ id_group_tax: 1 (number, required)
+ active: true (boolean, required)

### GroupsTaxesStructure
+ id_group_tax: 1 (number, required)
+ name_group_tax: A (string, required)

### PricesStructure
+ id_goods: 1 (number, required)
+ id_unit: 1 (number, required)
+ id_series: `-` (string, required)
+ id_price_level: 1 (number, required)
+ price: 100.00 (number, required)
+ min_price: 0 (number, required) 
+ max_price: 0 (number, required)
+ active: true (boolean, required)

### PriceLevelsStructure
+ id_price_level: 1 (number, required)
+ name_price_level: Закупочная (string, required)
+ active: true (boolean, required)

### UnitsStructure
+ id_goods: 1 (number, required)
+ id_unit: 1 (number, required)
+ name_unit: шт (string, required)
+ is_default: false (boolean, required)
+ rate: 1.000 (number, required)
+ type_unit: 3 (number, required)
+ max_count: 0.000 (number, required)
+ active: true (boolean, required)

### TypesUnitsStructure
+ type_unit: 2 (number, required)
+ name: Кратное 25% (string, required)

### SeriesStructure
+ id_goods: 5 (number, required)
+ id_series: 1 (string, required)
+ name_series: Синие (string, required)
+ active: true  (boolean, required)

### CountStructure
+ count: 10 (number, required) 

#Group Группы товаров 

## Дерево групп товаров [/api/groupsGoods{?active,unprotect_keys}]

### Получить все группы товаров в виде дерева [GET]

+ Parameters 

    + active (string, optional) - Если параметр присутствует и равен "true", то возвращается дерево, с использованием только активных групп товаров.

+ Response 200 (application/json)

    + Attributes (array[GroupsGoodsStructure])
    
### Добавить группу товаров [POST]
- Атрибут `id_group` в JSON-е запроса  игнорируется, если не указан параметр `unprotect_keys=true`.

+ Parameters

    + unprotect_keys (string,optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Request (application/json)

    + Attributes (GroupGoodsStructure)    
            
+ Response 201 (application/json)

    + Headers

            Location: /api/groupsGoods/1

    + Attributes (GroupGoodsStructure)    

    
## Группа товаров [/api/groupsGoods/{id_group}{?unprotect_keys}]

### Получить группу товаров [GET]
Получение группы товаров.

+ Parameters

    + id_group (number) - Код группы товаров - целое число

+ Response 200 (application/json)

    + Attributes (GroupGoodsStructure)
    
### Изменить группу товаров [PUT]
Изменение группы товаров. 
- Атрибут `id_group` в JSON-е запроса  игнорируется, если не указан параметр `unprotect_keys=true`.

+ Parameters

    + id_group (number) - Код группы товаров - целое число
    + unprotect_keys (string,optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (GroupGoodsStructure)
            
+ Response 200 (application/json)

    + Attributes (GroupGoodsStructure)
            
### Деактивировать группу товаров [DELETE]
Деактивация группы товаров

+ Parameters

    + id_group (number) - Код группы товаров - целое число

+ Response 204


#Group Товары

## Список товаров [/api/goods{?id_group,immediate_parent,active,offset,limit,unprotect_keys}]

### Получить все товары [GET]
Получение списка товаров. Если не указывать код группы, возвращаются все товары, если immediate_parent не равен "true", будут возвращены также товары, которые входят в подчиненные группы, указаной группы товаров 

+ Parameters

    + id_group (integer, optional) - Код группы товаров, к которой принадлежит товар
    + immediate_parent (string, optional) - Если параметр равен "true", то возвращаются товары, принадлежащие непосредственно к данной группе
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные товары.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[GoodsStructure])
    
    
### Добавить товар [POST]
Добавление нового товара. 
- Атрибут id_goods в JSON-е запроса игнорируется (значение будет установлено автоматически), если не указан параметр `unprotect_keys=true`
- В таблицу front.series будет добавлена запись с серией по умолчанию для данного товара ("-")

+ Parameters

    + unprotect_keys (string,optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (GoodsStructure)
            
            
+ Response 201 (application/json)

    + Headers

            Location: /api/goods/1

    + Attributes (GoodsStructure)
    
## Количество товаров [/api/goods/count{?id_group,immediate_parent,active}]

### Получить количество товаров [GET]
Возвращает количество записей 

+ Parameters

    + id_group (integer, optional) - Код группы товаров, к которой принадлежит товар
    + immediate_parent (string, optional) - Если параметр равен "true", то возвращаются товары, принадлежащие непосредственно к данной группе
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные товары.

+ Response 200 (application/json)

    + Attributes (CountStructure)

## Товар [/api/goods/{id_goods}{?unprotect_keys}]

### Получить товар [GET]
Получение товара по коду

+ Parameters

    + id_goods (integer, required) - Код товара

+ Response 200 (application/json)

    + Attributes (GoodsStructure)
            
### Изменить товар [PUT]
Изменение товара. 
- Атрибут id_goods в JSON-е запроса игнорируется, если не указан параметр `unprotect_keys=true`

+ Parameters

    + id_goods (integer, required) - Код товара
    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (GoodsStructure)
            
+ Response 200 (application/json)

    + Attributes (GoodsStructure)
            
### Деактивировать товар [DELETE]
Деактивация товара

+ Parameters

    + id_goods (integer, required) - Код товара

+ Response 204            


## Список атрибутов товаров [/api/goodsAttrs{?offset,limit}]

### Получить все записи атрибутов товаров [GET]
Получить список записей атрибутов товаров

+ Parameters

    + offset (integer,optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer,optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[GoodsAttrsStructure])  
    
## Количество атрибутов товаров [/api/goodsAttrs/count]

### Получить количество атрибутов товаров [GET]
Возвращает количество записей 

+ Response 200 (application/json)

    + Attributes (CountStructure)    
    
       
## Атрибуты товара [/api/goodsAttrs/{id_goods}{?unprotect_keys}]
TODO: При добавлении или изменении записи получаю ошибку: 
      Не определено свойство GoodsAttr.id_modificator_group.

### Добавить запись атрибутов товара [POST]
Добавление атрибутов для товара. 
**Значение поля id_goods автоматически не заполняется. Указывать в JSON-е тела запроса и использовать параметр `unprotect_keys=true`**

+ Parameters

    + id_goods (integer, required) - Код товара
    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (GoodsAttrsStructure)
            
+ Response 201 (application/json)

    + Headers

            Location: /api/goodsAttrs/1

    + Attributes (GoodsAttrsStructure)


### Получить атрибуты товара [GET]
Получение атрибутов для товара. 

+ Parameters

    + id_goods (integer, required) - Код товара
    
+ Response 200 (application/json)

    + Attributes (GoodsAttrsStructure)
            
### Изменить атрибуты товара [PUT]
Изменение атрибутов товара. Атрибут id_goods в JSON-е запроса игнорируется.

+ Parameters

    + id_goods (integer, required) - Код товара
    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (GoodsAttrsStructure)
            
+ Response 200 (application/json)

    + Attributes (GoodsAttrsStructure)     
    
    
#Group Штрих-коды

## Список штрих-кодов [/api/barCodes{?bar_code,active,offset,limit}]

### Получить все штрих-коды [GET]

+ Parameters

    + bar_code (integer, optional) - Штрих-код товара. Если указать, будет возвращен список для данного штрих-кода
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[BarCodesStructure])   

### Добавить штрих-код [POST]
Ключевые атрибуты `bar_code`, `id_goods`, `id_unit`, `ext_bar_code`, `id_series` в JSON-е запроса стандартно игнорирутся. 
**Для добавления штрих-кода использовать параметр `unprotect_keys=true` и указывать значения ключевых полей в теле запроса**.

+ Request (application/json)

    + Attributes (BarCodesStructure)  
                

+ Response 201 (application/json)

    + Headers

            Location: /api/barCodes/1/1/1/1/1

    + Attributes (BarCodesStructure)  
    
## Количество штрих-кодов [/api/barCodes/count{?id_goods,bar_code,active}]

### Получить количество штрих-кодов [GET]
Возвращает количество записей 

+ Parameters

    + id_goods (integer, optional) - Код товара
    + bar_code (string, optional) - Штрих-код
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные товары.

+ Response 200 (application/json)

    + Attributes (CountStructure)    
    
            
## Штрих-код [/api/barCodes/{bar_code}/{id_goods}/{id_unit}/{?ext_bar_code}/{?id_series}]

### Получить данные о штрих-коде [GET]
- Параметры `ext_bar_code`, `id_series` можно опускать, если для обоих используются значения по умолчанию.
- Для указания значения по умолчанию для параметра `ext_bar_code` или `id_series` использовать слово `default`

+ Parameters
    + bar_code (integer, required) - Штрих-код товара
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + ext_bar_code (string, optional) - Расширенный штрих-код (Для указания значения по умолчанию использовать слово `default`)
    + id_series (string, optional) - Код серии (Для указания значения по умолчанию использовать слово `default`)

+ Response 200 (application/json)

    + Attributes (BarCodesStructure)
    
            
### Изменить данные о штрих-коде [PUT]
Ключевые атрибуты `bar_code`, `id_goods`, `id_unit`, `ext_bar_code`, `id_series` в JSON-е запроса стандартно игнорирутся. 
- Для изменения ключевых полей использовать параметр `unprotect_keys=true`

+ Parameters
    + bar_code (integer, required) - Штрих-код товара
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + ext_bar_code (string, optional) - Расширенный штрих-код (Для указания значения по умолчанию использовать слово `default`)
    + id_series (string, optional) - Код серии (Для указания значения по умолчанию использовать слово `default`) 

+ Request (application/json)

    + Attributes (BarCodesStructure)
            
+ Response 200 (application/json)

    + Attributes (BarCodesStructure)
            
### Деактивировать данные о штрих-коде [DELETE]

+ Response 204     
    

#Group Контрагенты

## Список контрагентов [/api/clients{?supplier,buyer,active,offset,limit,unprotect_keys}]

### Получить список контрагентов [GET]
Получение списка контрагентов. Если не указаны дополнительные параметры, возвращаются сразу и поставщики, и покупатели.
Параметры supplier, buyer со значением true дают возможность получать отдельно списки поставщиков или покупателей

+ Parameters
    + supplier (string, optional) - Если параметр равен "true", то возвращается (добавляется запись) список покупателей 
    + buyer (string, optional) - Если параметр равен "true", то возвращается (добавляется запись) список ппоставщиков 
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные контрагенты.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[ClientsStructure])  
    

### Добавить контрагента [POST]
Добавление контрагента. Атрибут id_client в JSON-е запроса стандартно игнорируется.

+ Parameters

    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (ClientsStructure)  
            
+ Response 201 (application/json)
    
    + Headers

            Location: /api/client/1

    + Attributes (ClientsStructure)  
            
## Количество контрагентов [/api/clients/count{?is_supplier,is_buyer,active}]

### Получить количество контрагентов [GET]
Возвращает количество записей    

+ Parameters

    + is_supplier (string, optional) - Если параметр равен "true", то учитываются покупатели 
    + is_buyer (string, optional) - Если параметр равен "true", то учитываются поставщики 
    + active (string, optional) - Если параметр равен "true", то учитываются только активные контрагенты.

+ Response 200 (application/json)

    + Attributes (CountStructure)             
            
## Контрагент [/api/clients/{id_client}{?unprotect_keys}]

### Получить данные о контрагенте [GET]
Получение данных о клиенте по коду

+ Parameters

    + id_client (integer, required) - Код клиента

+ Response 200 (application/json)

    + Attributes (ClientsStructure)  
            
### Изменить данные о контрагенте [PUT]
Изменение данных о клиенте. Атрибут id_client в JSON-е запроса стандартно игнорируется.

+ Parameters

    + id_client (integer, required) - Код клиента
    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (ClientsStructure)  
            
+ Response 200 (application/json)

    + Attributes (ClientsStructure)  
            
### Деактивировать данные о контрагенте [DELETE]
Деактивация данных о контрагенте.

+ Parameters

    + id_client (integer, required) - Код клиента

+ Response 204     


#Group Налоги

## Список налогов [/api/taxes{?active,offset,limit,unprotect_keys}]

### Получить список налогов [GET]
Получение всех записей

+ Parameters

    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[TaxesStructure]) 

### Добавить налог [POST]
Добавление нового налога. Атрибут id_tax в JSON-е запроса стандартно игнорируется.

+ Parameters

    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (TaxesStructure) 
            
+ Response 200 (application/json)

    + Headers

            Location: /api/taxes/1

    + Attributes (TaxesStructure) 

    
## Количество налогов [/api/taxes/count{?active}]

### Получить количество налогов [GET]
Возвращает количество записей    

+ Parameters

    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
    
            
## Налог [/api/taxes/{id_tax}{?unprotect_keys}]

+ Parameters

    + id_tax (integer, required) - Код налога
    + unprotect_keys (string, optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

### Получить данные о налоге [GET]
Получение записи по коду

+ Response 200 (application/json)

    + Attributes (TaxesStructure) 
            
### Изменить данные о налоге [PUT]
Изменение данных о налоге. Атрибут id_tax в JSON-е запроса игнорируется.

+ Request (application/json)

    + Attributes (TaxesStructure) 
            
+ Response 200 (application/json)

    + Attributes (TaxesStructure) 
            
### Деактивировать данные о налоге [DELETE]

+ Response 204     


## Список групп налоговых ставок [/api/groupsTaxes{?offset,limit,active}]

### Получить список групп налоговых ставок [GET]
Получить список всех групп налоговых ставок

+ Parameters

    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.

+ Response 200 (application/json)

    + Attributes (array[GroupsTaxesStructure])   
    
### Добавить группу налоговых ставок [POST]
Добавление новой группы налоговых ставок.
- Атрибут `id_group_tax` в JSON-е запроса игнорируется (значение будет установлено автоматически), если не указан параметр `unprotect_keys=true`

+ Request (application/json)

    + Attributes (GroupsTaxesStructure) 
            
+ Response 200 (application/json)

    + Headers

            Location: /api/groupsTaxes/1

    + Attributes (GroupsTaxesStructure)   
    
    
## Количество групп налоговых ставок [/api/groupsTaxes/count{?active}]

### Получить количество налогов [GET]
Возвращает количество записей    

+ Parameters

    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
        

## Группа налоговых ставок [/api/groupsTaxes/{id_group_tax}]

+ Parameters
    + id_group_tax (integer, required) - Код группы налоговых ставок

### Получить данные о группе налоговых ставок [GET]
Получение записи по коду

+ Response 200 (application/json)

    + Attributes (GroupsTaxesStructure)     

### Изменить данные о группе налоговых ставок [PUT]
Изменение группы налоговых ставок.
- Атрибут `id_group_tax` в JSON-е запроса игнорируется, если не указан параметр `unprotect_keys=true`

+ Request (application/json)

    + Attributes (GroupsTaxesStructure) 
            
+ Response 200 (application/json)

    + Attributes (GroupsTaxesStructure) 

### Деактивировать данные о группе налоговых ставок [DELETE]

+ Response 204  
            
#Group Цены

## Список цен [/api/prices{?id_goods,active,offset,limit}]

### Получить все цены [GET]

+ Parameters

    + id_goods (integer, optional) - Код товара. Если указать, будет возвращен список цен для конкретного товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Attributes (array[PricesStructure])   

### Добавить цену [POST]
Ключевые атрибуты `id_goods`, `id_unit`, `id_price_level`, `id_series` в JSON-е запроса стандартно игнорирутся. 
**Для добавления цены использовать параметр `unprotect_keys=true` и указывать значения ключевых полей в теле запроса**.

+ Request (application/json)

    + Attributes (PricesStructure)  
                

+ Response 201 (application/json)

    + Headers

            Location: /api/prices/1/1/1/1

    + Attributes (PricesStructure)  
    
    
## Количество цен [/api/prices/count{?id_goods,active}]

### Получить количество цен [GET]
Возвращает количество записей    

+ Parameters

    + id_goods (integer, optional) - Код товара. Если указать, будет учитываются цены для конкретного товара
    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
        
    
## Цена [/api/price/{id_goods}/{id_unit}/{id_price_level}/{?id_series}]

### Получить данные о цене [GET]
Параметр `id_series`, опускается, если используется значение серии по умолчанию "-".

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + id_price_level (integer, required) - Код уровня цен
    + id_series (string, optional) - Код серии. Если не указан, предполагается "-"   

+ Response 200 (application/json)

    + Attributes (PricesStructure)
    
            
### Изменить данные о цене [PUT]
Ключевые атрибуты `id_goods`, `id_unit`, `id_price_level`, `id_series` в JSON-е запроса стандартно игнорирутся. 

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + id_price_level (integer, required) - Код уровня цен
    + id_series (string, optional) - Код серии. Если не указан, предполагается "-"   

+ Request (application/json)

    + Attributes (PricesStructure)
            
+ Response 200 (application/json)

    + Attributes (PricesStructure)
            
### Деактивировать данные о цене [DELETE]

+ Response 204     


#Group Уровни цен

## Список уровней цен [/api/priceLevels{?active,offset,limit}]

### Получить все уровни цен [GET]
Получение списка всех уровней цен

+ Parameters

    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей

+ Response 200 (application/json)

    + Attributes (array[PriceLevelsStructure])   
            
### Добавить уровень цен [POST]
Добавление уровня цен.  Атрибут `id_price_level` в JSON-е запроса стандартно игнорируется, если не указан параметр `unprotect_keys=true` (заполняется автоматически).

+ Request (application/json)

    + Attributes (PriceLevelsStructure)   
                
+ Response 201 (application/json)

    + Headers

            Location: /api/priceLevels/1

    + Attributes (PriceLevelsStructure)      
    
    
## Количество уровней цен [/api/priceLevels/count{?active}]

### Получить количество уровней цен [GET]
Возвращает количество записей    

+ Parameters

    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
            

## Уровень цен [/api/priceLevels/{id_price_level}]

+ Parameters

    + id_price_level (integer, required) - Код уровня цен

### Получить данные об уровне цен [GET]
Получение данных об уровне цен

+ Response 200 (application/json)

    + Attributes (PriceLevelsStructure)   

### Изменить данные об уровне цен [PUT]
Атрибут `id_price_level` в JSON-е запроса стандартно игнорируется, если не указан параметр `unprotect_keys=true`

+ Request (application/json)

    + Attributes (PriceLevelsStructure)  
            
+ Response 200 (application/json)

    + Attributes (PriceLevelsStructure)  
            
### Деактивировать данные о цене [DELETE]

+ Response 204     


#Group Единицы измерения

## Список единиц измерения для товара [/api/units{?id_goods,active,offset,limit}]

### Получить все единицы измерения [GET]
Получение списка всех единиц измерения. Если указан параметр id_goods, возвращаются единицы измерения для конкретного товара

+ Parameters

    + id_goods (integer, optional) - Код товара, Если указан, возвращаются единицы измерения только для данного товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json) 

    + Attributes (array[UnitsStructure])   
    
### Добавить единицу измерения [POST]
Добавление единицы измерения.  Атрибуты `id_goods`, `id_unit` в JSON-е запроса стандартно игнорирутся. 
Параметр `id_goods` следует указывать в параметрах запроса, параметр `id_unit` заполняется автоматически.
При использовании параметра `unprotect_keys=true` необходимо указывать значения ключевых полей в теле запроса.

+ Request (application/json)

    + Attributes (UnitsStructure)   
                

+ Response 201 (application/json)

    + Headers

            Location: /api/units/1/1

    + Attributes (UnitsStructure)          

    
## Количество единиц измерения [/api/units/count{?id_goods,active}]

### Получить количество единиц измерения  [GET]
Возвращает количество записей    

+ Parameters

    + id_goods (integer, optional) - Код товара, Если указан, учитываются единицы измерения только для данного товара
    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
            

## Единица измерения [/api/units/{id_goods}/{id_unit}]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения

### Получить данные о единице измерения [GET]
Получение данных о единице измерения по коду товара и коду единицы измерения

+ Response 200 (application/json)

    + Attributes (UnitsStructure)
            
### Изменить данные о единице измерения [PUT]
Изменение данных о единице измерения. 
Атрибуты `id_goods`, `id_unit` в JSON-е запроса стандартно игнорирутся. 

+ Request (application/json)

    + Attributes (UnitsStructure)
            
+ Response 200 (application/json)

    + Attributes (UnitsStructure)
            
### Деактивировать данные о единице измерения [DELETE]

+ Response 204         


## Список типов единиц измерения [/api/typesUnits]

### Получить все типы единиц измерения [GET]
Получение списка типов единиц измерения товаров.

+ Response 200 (application/json)
    
    + Attributes (array[TypesUnitsStructure])
            

#Group Серии

## Список серий [/api/series{?id_goods,active,offset,limit,unprotect_keys}]

### Получить все серии [GET]
Получение списка всех серий. Если указан параметр id_goods, возвращаются серии для конкретного товара

+ Parameters

    + id_goods (integer, required) - Код товара, Если указан, возвращаются серии только для данного товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные записи.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей

+ Response 200 (application/json)

    + Attributes (array[SeriesStructure])   
    
### Добавить серию для товара [POST]
Добавление новой серии для товара.  
- Атрибуты `id_goods`, `id_series` в JSON-е запроса игнорируется, если не указан параметр `unprotect_keys=true`.
Значение `id_series` будет установлено автоматически. Значение `id_goods` передается соответствующим параметром. 
- Добавление записи серии по умолчанию ("-") происходит автоматически при создании нового товара.

+ Parameters

    + id_goods (integer, required) - Код товара 
    + unprotect_keys (string,optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (SeriesStructure)   
                
+ Response 201 (application/json)

    + Headers

            Location: /api/series/1/1

    + Attributes (SeriesStructure) 
   

    
## Количество серий [/api/series/count{?id_goods,active}]

### Получить количество серий  [GET]
Возвращает количество записей    

+ Parameters

    + id_goods (integer, optional) - Код товара, Если указан, учитываются серии только для данного товара
    + active (string, optional) - Если параметр равен "true", то учитываются только активные записи.

+ Response 200 (application/json)

    + Attributes (CountStructure)      
            
   
   
            
## Серия [/api/series/{id_goods}/{id_series}{?unprotect_keys}]

### Получить данные о серии товара [GET]
Получение данных о серии товара по коду товара и коду серии

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_series (string, optional) - Код серии. Если не указан, предполагается значение по умолчанию ("-") 

+ Response 200 (application/json)

    + Attributes (SeriesStructure) 
            
### Изменить данные о серии товара [PUT]
Изменение данных о серии товара по коду товара и коду серии

+ Parameters

    + id_goods (integer, required) - Код товара
    + id_series (string, optional) - Код серии. Если не указан, предполагается значение по умолчанию ("-") 
    + unprotect_keys (string,optional) - Если параметр существует и равен "true", в операциях создания/редактирования значения ключевого поля не игнорируются

+ Request (application/json)

    + Attributes (SeriesStructure) 
            
+ Response 200 (application/json)

    + Attributes (SeriesStructure) 
            
### Деактивировать данные о серии товара [DELETE]

Деактивация данных о серии

+ Parameters

    + id_goods (integer, required) - Код товара
    + id_series (string, optional) - Код серии. Если не указан, предполагается значение по умолчанию ("-") 

+ Response 204