FORMAT: 1A
HOST: http://private-01ace7-scout7.apiary-mock.com/

# Scout

API для приложения Scout

#Group Группы товаров 

## Дерево групп товаров [/api/groupsGoods{?active}]

### Получить все группы товаров в виде дерева [GET]

+ Parameters 
    + active (string, optional) - Если параметр присутствует и равен "true", то возвращается дерево, с использованием только активных групп товаров.

+ Response 200 (application/json)

    + Body

            [
                {
                    "id_group": 1,
                    "name_group": "Пополнение счета",
                    "id_owner_group": 0,
                    "active": true,
                    "id_image": null,
                    "children": [
                        {
                            "id_group": 2,
                            "name_group": "Для пополнения",
                            "id_owner_group": 1,
                            "active": true,
                            "id_image": null,
                            "children": []
                        },
                        {
                            "id_group": 3,
                            "name_group": "Пополнение с комиссией",
                            "id_owner_group": 1,
                            "active": true,
                            "id_image": null,
                            "children": []
                        }
                    ]
                },
                {
                    "id_group": 4,
                    "name_group": "Брюки",
                    "id_owner_group": 0,
                    "active": true,
                    "id_image": null,
                    "children": []
                }
            ]
        
    + Schema 
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type": "object",
                "properties": {
                    "id_group": {
                        "type": "integer"
                    },
                    "name_group": {
                        "type": "string"
                    },
                    "active": {
                        "type":"boolean"
                    },
                    "children": {
                        "type":"array"
                        "items": {
                            "type":"object"
                        }
                    }
                }
            }

## Группа товаров [/api/groupsGoods/{id_group}]

Параметр id_group при получении, изменении, деактивировании группы указывает на целевую группу. 
При добавлении группы - на родительскую группу товаров

+ Parameters
    + id_group (number) - Код группы товаров - целое число

### Добавить группу товаров [POST]
Добавление группы товаров. Параметр id_group указывает на родительскую группу (0 - корневая группа товаров)

+ Request (application/json)

    + Request (application/json)

    + Attributes
    
        + name_group: Алкогольные напитки (required)
            
+ Response 201 (application/json)

    + Attributes
    
        + id_group: 4 (number, required)
        + id_owner_group: 0 (number, required)
        + name_group: Алкогольные напитки (string, required)
        + active: true (boolean, required)

    
### Получить группу товаров [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/groups_goods/1

    + Body

                {
                    "id_group": 1,
                    "name_group": "Пополнение счета",
                    "id_owner_group": 0,
                    "active": true,
                    "id_image": null
                }
            
    + Schema 
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type": "object",
                "properties": {
                    "id_group": {
                        "type": "integer"
                    },
                    "name_group": {
                        "type": "string"
                    },
                    "active": {
                        "type":"boolean"
                    },
                    "children": {
                        "type":"array"
                        "items": {
                            "type":"object"
                        }
                    }
                }
            }
    
### Изменить группу товаров [PUT]

+ Request (application/json)

            { 
                "name_group":"Алкогольные напитки"
                "active":true,
            }
            
+ Response 204
            
### Деактивировать группу товаров [DELETE]

+ Response 204


#Group Товары

## Список товаров [/api/goods{?id_group,immediate_parent,active,offset,limit}]

### Получить все товары [GET]

Получение списка товаров. Если не указывать код группы, возвращаются все товары, если immediate_parent не равен "true", будут возвращены также товары, которые входят в подчиненные группы, указаной группы товаров 

+ Parameters
    + id_group (integer, optional) - Код группы товаров, к которой принадлежит товар
    + immediate_parent (string, optional) - Если параметр равен "true", то возвращаются товары, принадлежащие непосредственно к данной группе
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные товары.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Body
        
            [
                {
                    "id_goods":1,
                    "id_group":1,
                    "id_tax":1,
                    "name_goods":"Хлеб черный",
                    "sort_order":"",
                    "id_printer":1,
                    "type_goods":0,
                    "active":true
                },
                {
                    "id_goods":2,
                    "id_group":1,
                    "id_tax":1,
                    "name_goods":"Хлеб белый",
                    "sort_order":"",
                    "id_printer":1,
                    "type_goods":0,
                    "active":true
                },
                {
                    "id_goods":3,
                    "id_group":1,
                    "id_tax":1,
                    "name_goods":"Батон",
                    "sort_order":"",
                    "id_printer":1,
                    "type_goods":0,
                    "active":true
                }
            ]
    
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type":"array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id_goods": {
                            "type": "integer"
                        },
                        "id_group": {
                            "type": "integer"
                        },
                        "id_tax": {
                            "type": "integer"
                        },
                        "name_goods": {
                            "type": "string"
                        },
                        "sort_order": {
                            "type": "string"
                        },
                        "id_printer": {
                            "type": "integer"
                        },
                        "type_goods": {
                            "type": "integer"
                        },
                        "active": {
                            "type":"boolean"
                        }
                    }
                }
            }
    
    
### Добавить товар [POST]

Добавление нового товара

+ Request (application/json)

    + Body

            {
                    "id_group":1,
                    "id_tax":1,
                    "name_goods":"Булочка с маком",
                    "sort_order":"",
                    "id_printer":1,
                    "type_goods":0,
                    "active":true
                },
            
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type":"array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id_group": {
                            "type": "integer"
                        },
                        "id_tax": {
                            "type": "integer"
                        },
                        "name_goods": {
                            "type": "string"
                        },
                        "sort_order": {
                            "type": "string"
                        },
                        "id_printer": {
                            "type": "integer"
                        },
                        "type_goods": {
                            "type": "integer"
                        },
                        "active": {
                            "type":"boolean"
                        }
                    }
                }
            }
            
            
+ Response 201 (application/json)

     + Body

            {
                    "id_goods":5,
                    "id_group":1,
                    "id_tax":1,
                    "name_goods":"Булочка с маком",
                    "sort_order":"",
                    "id_printer":1,
                    "type_goods":0,
                    "active":true
                }
            
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type":"array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id_goods": {
                            "type": "integer"
                        },
                        "id_group": {
                            "type": "integer"
                        },
                        "id_tax": {
                            "type": "integer"
                        },
                        "name_goods": {
                            "type": "string"
                        },
                        "sort_order": {
                            "type": "string"
                        },
                        "id_printer": {
                            "type": "integer"
                        },
                        "type_goods": {
                            "type": "integer"
                        },
                        "active": {
                            "type":"boolean"
                        }
                    }
                }
            }


## Товар [/api/goods/{id_goods}]

Получение товара по коду

+ Parameters
    + id_goods (integer, required) - Код товара

### Получить товар [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/goods/1

    + Body

            {
                "id_goods":5,
                "id_group":1,
                "id_tax":1,
                "name_goods":"Булочка с маком",
                "sort_order":"",
                "id_printer":1,
                "type_goods":0,
                "active":true
            }
            
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type":"array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id_goods": {
                            "type": "integer"
                        },
                        "id_group": {
                            "type": "integer"
                        },
                        "id_tax": {
                            "type": "integer"
                        },
                        "name_goods": {
                            "type": "string"
                        },
                        "sort_order": {
                            "type": "string"
                        },
                        "id_printer": {
                            "type": "integer"
                        },
                        "type_goods": {
                            "type": "integer"
                        },
                        "active": {
                            "type":"boolean"
                        }
                    }
                }
            }
            
### Изменить товар [PUT]

+ Parameters
    + id_goods (integer, required) - Код товара

+ Request (application/json)

            {
                "id_group":1,
                "id_tax":1,
                "name_goods":"Булочка с маком",
                "sort_order":"",
                "id_printer":1,
                "type_goods":0,
                "active":true
            }
            
+ Response 204
            
### Деактивировать товар [DELETE]

+ Response 204            

## Атрибуты товара [/api/goods/{id_goods}/attributes]


+ Parameters
    + id_goods (integer, required) - Код товара

### Получить атрибуты товара [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/goods/1/attributes

    + Body

            {
                "id_goods":5,
                "control_rest":true,
                "extern_service_id":0,
                "print_name_goods":"Булочка с маком",
                "free_price":false,
                "only_bar_code":false,
                "control_showcase":false,
                "min_order":0.00,
                "id_client":1,
                "use_series":false,
                "id_text":null,
                "id_modificator_group":0
            }
            
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "type":"array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id_goods": {
                            "type": "integer"
                        },
                        "control_rest": {
                            "type": "boolean"
                        },
                        "extern_service_id": {
                            "type": "integer"
                        },
                        "print_name_goods": {
                            "type": "string"
                        },
                        "free_price": {
                            "type": "boolean"
                        },
                        "only_bar_code": {
                            "type": "boolean"
                        },
                        "control_showcase": {
                            "type": "boolean"
                        },
                        "min_order": {
                            "type":"float"
                        },
                        "id_client": {
                            "type":"integer"
                        },
                        ,
                        "use_series": {
                            "type":"boolean"
                        },
                        "id_text": {
                            "type":"integer"
                        },
                        "id_modificator_group": {
                            "type":"integer"
                        }
                        
                    }
                }
            }
            
### Изменить атрибуты товара [PUT]

+ Parameters
    + id_goods (integer, required) - Код товара

+ Request (application/json)

            {
                "control_rest":true,
                "extern_service_id":0,
                "print_name_goods":"Булочка с маком",
                "free_price":false,
                "only_bar_code":false,
                "control_showcase":false,
                "min_order":0.00,
                "id_client":1,
                "use_series":false,
                "id_text":null,
                "id_modificator_group":0
            }
            
+ Response 204            

#Group Контрагенты

## Список контрагентов [/api/clients{?supplier,active,offset,limit}]

### Получить список контрагентов [GET]

+ Parameters
    + supplier (string, optional) - Если параметр равен "true", то возвращается (добавляется запись) список покупателей, если "false" или опущен - список продавцов 
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные контрагенты.
    + offset (integer, optional) - Возвращать данные, начиная с указанного номера записи
    + limit (integer, optional) - Возвращать указанное количество записей
    
+ Response 200 (application/json)

    + Body
        
            [
                {
                    "id_client":1,
                    "name_client":"Иванов Иван Иванович"
                    "can_return":true,
                    "id_price_level":null
                    "active":true
                },
                {
                    "id_client":2,
                    "name_client":"Петров Петр Петрович"
                    "can_return":true,
                    "id_price_level":null
                    "active":true
                },
                {
                    "id_client":3,
                    "name_client":"Сидоров Сидор Сидорович"
                    "can_return":true,
                    "id_price_level":null
                    "active":true
                }
            ]

### Добавить контрагента [POST]

+ Request (application/json)

    + Body

            {
                "name_client":"Иванов Иван Иванович"
                "can_return":true,
                "id_price_level":null
                "active":true
            }
            
+ Response 201 (application/json)

     + Body

            {
                "id_client":1,
                "name_client":"Иванов Иван Иванович"
                "can_return":true,
                "id_price_level":null
                "active":true
            }
            
## Контрагент [/api/client/{id_client}]

+ Parameters
    + id_client (integer, required) - Код клиента

### Получить данные о контрагенте [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/client/1

    + Body

            {
                "id_client":1,
                "name_client":"Иванов Иван Иванович"
                "can_return":true,
                "id_price_level":null
                "active":true
            }
            
    
            
### Изменить данные о контрагенте [PUT]

+ Parameters
    + id_client (integer, required) - Код клиента

+ Request (application/json)

            {
                "name_client":"Иванов Иван Иванович"
                "can_return":true,
                "id_price_level":1
                "active":true
            }
            
+ Response 204
            
### Деактивировать данные о контрагенте [DELETE]

+ Response 204     


#Group Налоги

## Список налогов [/api/taxes{?active}]

### Получить список налогов [GET]

+ Parameters
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные налоги.
    
+ Response 200 (application/json)

    + Body
        
            [
                {
                    "id_tax":1,
                    "rate_tax":0.00,
                    "name_tax":"Без НДС",
                    "id_group_tax":1,
                    "active":true
                },
                {
                    "id_tax":2,
                    "rate_tax":5.00,
                    "name_tax":"Единый налог",
                    "id_group_tax":2,
                    "active":true
                },
                {
                    "id_tax":3,
                    "rate_tax":20.00,
                    "name_tax":"НДС 20%",
                    "id_group_tax":3,
                    "active":true
                }
            ]

### Добавить налог [POST]

+ Request (application/json)

    + Body

            {
                "rate_tax":20.00,
                "name_tax":"НДС 20%",
                "id_group_tax":3,
                "active":true
            }
            
+ Response 201 (application/json)

     + Body

            {
                "id_tax":3,
                "rate_tax":20.00,
                "name_tax":"НДС 20%",
                "id_group_tax":3,
                "active":true
            }
            
## Налог [/api/tax/{id_tax}]

+ Parameters
    + id_tax (integer, required) - Код налога

### Получить данные о налоге [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/tax/1

    + Body

            {
                "id_tax":1,
                "rate_tax":0.00,
                "name_tax":"Без НДС",
                "id_group_tax":1,
                "active":true
            }
            
    
            
### Изменить данные о налоге [PUT]

+ Parameters
    + id_tax (integer, required) - Код налога

+ Request (application/json)

    + Body

            {
                "rate_tax":1,
                "name_tax":"Без НДС",
                "id_group_tax":1,
                "active":true
            }
            
+ Response 204
            
### Деактивировать данные о налоге [DELETE]

+ Response 204     

## Список групп налоговых ставок [/api/group_tax]

### Получить список групп налоговых ставок [GET]

+ Response 200 (application/json)

    + Body

            [
                {
                    "id_group_tax":"1",
                    "name_group_tax":"A"
                },
                {
                    "id_group_tax":"2",
                    "name_group_tax":"B"
                },
                {
                    "id_group_tax":"3",
                    "name_group_tax":"C"
                },
                {
                    "id_group_tax":"4",
                    "name_group_tax":"D"
                },
                {
                    "id_group_tax":"5",
                    "name_group_tax":"E"
                },
                {
                    "id_group_tax":"6",
                    "name_group_tax":"B2"
                }
            ]

## Группа налоговых ставок [/api/group_tax/{id_group_tax}]

+ Parameters
    + id_group_tax (integer, required) - Код группы налоговых ставок

### Получить данные о группе налоговых ставок [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/group_tax/1

    + Body
    
            {
                "id_group_tax":"1",
                "name_group_tax":"A"
            }
            
#Group Цены

## Список цен для товара [/api/prices{id_goods}{?active}]

### Получить все цены для товара [GET]

+ Parameters
    + id_goods (integer, required) - Код товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные цены.
    
+ Response 200 (application/json)

    + Body
        
            [
                {
                    "id_goods":1,
                    "id_unit":1,
                    "id_series":"-",
                    "id_price_level":1,
                    "price":100.00,
                    "min_price":null,
                    "max_price":null,
                    "wholesale_count":null,
                    "wholesale_price":null,
                    "active":true
                },
                {
                    "id_goods":1,
                    "id_unit":1,
                    "id_series":"-",
                    "id_price_level":2,
                    "price":120.00,
                    "min_price":null,
                    "max_price":null,
                    "wholesale_count":null,
                    "wholesale_price":null,
                    "active":true
                },
                {
                    "id_goods":1,
                    "id_unit":1,
                    "id_series":"-",
                    "id_price_level":3,
                    "price":140.00,
                    "min_price":null,
                    "max_price":null,
                    "wholesale_count":null,
                    "wholesale_price":null,
                    "active":true
                }
            
            ]
            
### Добавить цену [POST]

+ Request (application/json)

    + Body
    
            {
                "id_unit":1,
                "id_series":"-",
                "id_price_level":1,
                "price":100.00,
                "min_price":null,
                "max_price":null,
                "wholesale_count":null,
                "wholesale_price":null,
                "active":true
            }
                

+ Response 201 (application/json)

    + Body

            {
                "id_goods":1,
                "id_unit":1,
                "id_series":"-",
                "id_price_level":1,
                "price":100.00,
                "min_price":null,
                "max_price":null,
                "wholesale_count":null,
                "wholesale_price":null,
                "active":true
            
            }
            
## Цена [/api/price/{id_goods,id_unit,id_series}]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + id_series (integer, required) - Код серии    

### Получить данные о цене [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/price/1/1/1

    + Body

            {
                "id_goods":1,
                "id_unit":1,
                "id_series":"-",
                "id_price_level":1,
                "price":100.00,
                "min_price":null,
                "max_price":null,
                "wholesale_count":null,
                "wholesale_price":null,
                "active":true
            }
            
    
            
### Изменить данные о цене [PUT]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения
    + id_series (integer, required) - Код серии 

+ Request (application/json)

    + Body

            {
                "id_goods":1,
                "id_unit":1,
                "id_series":"-",
                "id_price_level":1,
                "price":100.00,
                "min_price":null,
                "max_price":null,
                "wholesale_count":null,
                "wholesale_price":null,
                "active":true
            }
            
+ Response 204
            
### Деактивировать данные о цене [DELETE]

+ Response 204     


#Group Уровни цен

## Список уровней цен [/api/price_levels{?active}]

### Получить все уровни цен [GET]

+ Parameters
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные уровни цен.

+ Response 200 (application/json)

    + Body
        
            [
                {
                    "id_price_level":1,
                    "name_price_level":"Оптовая",
                    "active":true
                },
                {
                    "id_price_level":2,
                    "name_price_level":"Розничная",
                    "active":true
                }
            ]
            
### Добавить уровень цен [POST]

+ Request (application/json)

    + Body
    
            {
                "name_price_level":"Оптовая",
                "active":true
            }
                

+ Response 201 (application/json)

    + Body

            {
                "id_price_level":1,
                "name_price_level":"Оптовая",
                "active":true
            }          

## Уровень цен [/api/price_level/{id_price_level}]

### Получить данные об уровне цен [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/price_level/1

    + Body

            {
                "id_price_level":1,
                "name_price_level":"Оптовая",
                "active":true
            }

### Изменить данные об уровне цен [PUT]

+ Parameters
    + id_price_level (integer, required) - Код уровня цен

+ Request (application/json)

    + Body

            {
                "id_price_level":1,
                "name_price_level":"Оптовая",
                "active":true
            }
            
+ Response 204
            
### Деактивировать данные о цене [DELETE]

+ Response 204     

#Group Единицы измерения

## Список единиц измерения для товара [/api/units{id_goods}{?active}]

### Получить все единицы измерения для товара [GET]

+ Parameters
    + id_goods (integer, required) - Код товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные единицы измерения.
    
+ Response 200 (application/json)
    
    + Body
    
            [
                {
                    "id_goods":1,
                    "id_unit":1,
                    "name_unit":"шт",
                    "is_default":true,
                    "rate":1,
                    "type_unit":1,
                    "max_count":0,
                    "active":true
                },
                {
                    "id_goods":1,
                    "id_unit":2,
                    "name_unit":"кг",
                    "is_default":false,
                    "rate":1,
                    "type_unit":3,
                    "max_count":0,
                    "active":true
                }
            ]
            
### Добавить единицу измерения [POST]

+ Request (application/json)

    + Body
    
            {
                "id_goods":1,
                "name_unit":"шт"
                "is_default":true,
                "rate":1,
                "type_unit":1,
                "max_count":0,
                "active":true
            },
                

+ Response 201 (application/json)

    + Body

            {
                "id_goods":1,
                "id_unit":1,
                "name_unit":"шт"
                "is_default":true,
                "rate":1,
                "type_unit":1,
                "max_count":0,
                "active":true
            }            

## Единица измерения [/api/unit/{id_goods,id_unit}]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения

### Получить данные о единице измерения [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/price/1/1

    + Body
    
            {
                "id_goods":1,
                "id_unit":1,
                "name_unit":"шт"
                "is_default":true,
                "rate":1,
                "type_unit":1,
                "max_count":0,
                "active":true
            } 
            
### Изменить данные о единице измерения [PUT]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_unit (integer, required) - Код единицы измерения

+ Request (application/json)

    + Body

            {
                "id_goods":1,
                "id_unit":1,
                "name_unit":"шт"
                "is_default":true,
                "rate":1,
                "type_unit":1,
                "max_count":0,
                "active":true
            }
            
+ Response 204
            
### Деактивировать данные о единице измерения [DELETE]

+ Response 204         


## Список типов единиц измерения [/api/types_units]

### Получить все типы единиц измерения [GET]

+ Response 200 (application/json)
    
    + Body
    
            [
                {
                    "type_unit":1,
                    "name":"только целое"
                },
                {
                    "type_unit":2,
                    "name":"50% или 25%"
                },
                {
                    "type_unit":3,
                    "name":"дробное"
                }
            ]
            

#Group Серии

## Список серий для товара [/api/series{id_goods}{?active}]

### Получить все серии для товара [GET]

+ Parameters
    + id_goods (integer required) - Код товара
    + active (string, optional) - Если параметр равен "true", то возвращаются только активные серии.

+ Response 200 (application/json)

    + Body
        
            [ 
                {
                    "id_goods":1,
                    "id_series":"-",
                    "name_series":"-",
                    "active":true
                },
                {
                    "id_goods":1,
                    "id_series":"1",
                    "name_series":"Белые",
                    "active":true
                },
                {
                    "id_goods":1,
                    "id_series":"2",
                    "name_series":"Синие",
                    "active":true
                },
                                {
                    "id_goods":1,
                    "id_series":"3",
                    "name_series":"Красные",
                    "active":true
                }
            ]
    
### Добавить серию для товара [POST]

+ Request (application/json)

    + Body
    
            {
                "id_series":"1",
                "id_goods":1,
                "name_series":"Белые",
                "active":true
            }
                
+ Response 201 (application/json)

    + Body

            {
                "id_goods":1,
                "id_series":"1",
                "name_series":"Белые",
                "active":true
            }  
   
            
## Серия [/api/series/{id_goods,id_series}]

### Получить данные о серии товара [GET]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_series (string, required) - Код серии 

+ Response 200 (application/json)

    + Headers

            Location: /api/series/1/1

    + Body         
    
            {
                "id_goods":1,
                "id_series":"1",
                "name_series":"Белые",
                "active":true
            } 
            
### Изменить данные о серии товара [PUT]

+ Parameters
    + id_goods (integer, required) - Код товара
    + id_series (string, required) - Код серии 

+ Request (application/json)

    + Body

            {
                "id_goods":1,
                "name_series":"Белые",
                "active":true
            } 
            
+ Response 204
            
### Деактивировать данные о серии товара [DELETE]

+ Response 204