FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Scout

API для приложения Scout

#Group Группы товаров 

## Дерево групп товаров [/api_group_goods/{?active}]

### Получить все группы товаров в виде дерева [GET]

+ Parameters 
    + active (string, optional) - Если параметр равен "true", то возвращается дерево, с использованием только активных групп товаров.

+ Response 200 (application/json)

        [ 
            {
                "id_group": 0,
                "name_group": "Корневая группа товаров",
                "active":true,
                "children": 
                [
                    { 
                        "id_group":1,
                        "name_group":"Хлебобулочные изделия",
                        "active":true,
                        "children": []
                    },
                    { 
                        "id_group":2,
                        "name_group":"Мясо",
                        "active":true,
                        "children": []
                    }
                                        { 
                        "id_group":3,
                        "name_group":"Безалкогольные напитки",
                        "active":true,
                        "children": []
                    }
                ]
            }
        ]

## Группа товаров [/api_group_goods/{id_group}]

Параметр id_group при получении, изменении, деактивировании группы указывает на целевую группу. 
При добавлении группы - на родительскую группу товаров

+ Parameters
    + id_group (number) - Код группы товаров - целое число

### Получить группу товаров [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api_group_goods/1

    + Body

            { 
                "id_group":1,
                "name_group":"Хлебобулочные изделия",
                "active":true,
                "children": []
            },
            
### Добавить группу товаров [POST]

+ Request (application/json)

            { 
                "name_group":"Алкогольные напитки"
            }
            
+ Response 201 (application/json)

            { 
                "id_group":4,
                "name_group":"Алкогольные напитки",
                "active":true,
                "children": []
            }

### Изменить группу товаров [PUT]

+ Request (application/json)

            { 
                "name_group":"Алкогольные напитки"
                "active":true,
            }
            
+ Response 204
            
### Деактивировать группу товаров [DELETE]

+ Response 204

## Перемещение группы товаров [/api_group_goods/id_group/{id_group}/id_parent_group/{id_parent_group}]

Перемещает группу товаров от одного родителя к другому

+ Parameters
    + id_group (number) - Код группы товаров - целое число
    + id_parent_group (number) - Код родительской группы, куда нужно переместить группу товаров 

### Переместить группу товаров [PUT]

+ Response 204